### PR TITLE
Added Portuguese translation

### PR DESCRIPTION
**Pull request by WadsonPontes**
Added Portuguese translation

### CODE REVIEW

**Review by Mrbysco — CHANGES_REQUESTED** [review]
Please update the translation with the missing values (See [en_us.json](https://github.com/Mrbysco/ChocoCraft4/blob/1.18.x/src/generated/resources/assets/chococraft/lang/en_us.json) )

**Comment by WadsonPontes** [comment]
Are the following lines discontinued?

item.chococraft.chocopedia.tooltip
chococraft.general.world
chococraft.general.world.gysahlgreenspawnweight
chococraft.general.gysahlgreenpatchsize

**Comment by Mrbysco** [comment]
> Are the following lines discontinued?
> 
> item.chococraft.chocopedia.tooltip chococraft.general.world chococraft.general.world.gysahlgreenspawnweight chococraft.general.gysahlgreenpatchsize

Yes, the world lines were config translations which nowadays aren't used. And the tooltip was removed as there's no stats screen anymore

**Review by Mrbysco — APPROVED** [review]
Looks good to me

**Pull request merged**
