### PR TITLE
Guide Book Visual Clean Up + Whistle Entry

### PR DESCRIPTION
**Pull request by kingkuys2123**

### CODE REVIEW

**Comment by Mrbysco** [comment]
Are you aware that all of the patchouli integration is datagenned, which means once I run the datagen I'd probably end up overwriting these? I'll have to recreate these with the datagen in order for them to stay

**Comment by Mrbysco** [comment]
I've manually implemented some of the clean-up

**Comment by kingkuys2123** [comment]
okayyy, thanks 😄

**Comment by kingkuys2123** [comment]
You should delete the [saddle](https://github.com/Mrbysco/ChocoCraft4/blob/arch/1.19.2/common/src/main/resources/data/chococraft/patchouli_books/chocopedia/en_us/entries/gysahls/saddle.json) entry inside [gysahls](https://github.com/Mrbysco/ChocoCraft4/tree/arch/1.19.2/common/src/main/resources/data/chococraft/patchouli_books/chocopedia/en_us/entries/gysahls) patchouli folder @Mrbysco

**Comment by Mrbysco** [comment]
> You should delete the saddle entry inside gysahls patchouli folder

Will do next version

**Pull request closed without merging**
